### ISSUE TITLE
KAS configuration file with stable commit for respective projects

### ISSUE THREAD

**Issue by sbanerjee-quic** [quic-yocto/meta-qcom-hwe#21]
Need to define a configuration file that captures the known stable commits for following projects:

- meta-qcom
- poky

This should helpful for user who want to work on a known stable checkout on the main.

**Comment by quaresmajose** [comment]
There some discussion about this on https://github.com/quic-yocto/meta-qcom-hwe/issues/13#issuecomment-2346390494

> About the lock:
running kas with --lock can improve this situation but for that it might be better to have an external repository (like quic-yocto/ci-manifest.git) just to save the hashes on the kas yaml. this way we don't pollute the local kas config of the bsp layer and not force the users to a specific version.

Yeah, that is my thinking as well. We can probably always use the latest in PRs and generate a lock file after the merge happens, publishing into another external repo.

**Comment by ricardosalveti** [comment]
> Yeah, that is my thinking as well. We can probably always use the latest in PRs and generate a lock file after the merge happens, publishing into another external repo.

For now can you look at automatically generating the lock files (guess via kas dump) and making it available in deploy as well? We will store the builds over NFS (for CI and developer access), so we can make the lock files available as part of the builds.
