### ISSUE TITLE
Nightly CI run schedule

### ISSUE THREAD

**Issue by sbanerjee-quic** [quic-yocto/meta-qcom-hwe#24]
Need a nightly CI job to track health of the tip of the tree.

**Comment by doanac** [comment]
sure. i'll knock it out.

**Comment by ricardosalveti** [comment]
I believe we just need to push the change as @quic-yocto-ci, as the daily notifications are sent to the one that created it, from the github docs.

**Comment by ricardosalveti** [comment]
Now that the default branch was changed to main, it is showing up at https://github.com/quic-yocto/meta-qcom-hwe/actions/workflows/nightly-build.yml.
