### ISSUE TITLE
Switch default branch to 'main'

### ISSUE THREAD

**Issue by ricardosalveti** [quic-yocto/meta-qcom-hwe#30]
At the moment the default branch is 'kirkstone', which is the current supported branch for Qualcomm Linux 1.1 and 1.2.

It would be better to switch the default to 'main' instead, as github has a few restrictions to workflows created on branches that are not the default, like https://github.com/orgs/community/discussions/16107.

As this can impact the documentation (users would need to clone the right branch when consuming Qcom Linux), tracking this as an issue.

**Comment by ricardosalveti** [comment]
@doanac @mynameistechno fyi

**Comment by mynameistechno** [comment]
If the README on main branch is clear and mentions where/how folks should use kirkstone vs main, seems fine to me. I wonder if there are any dependencies (e.g. Dockerfiles, QC Linux documentation) outside of GitHub that don't explicitly checkout the kirkstone branch?

**Comment by sbanerjee-quic** [comment]
> At the moment the default branch is 'kirkstone', which is the current supported branch for Qualcomm Linux 1.1 and 1.2.
> 
> It would be better to switch the default to 'main' instead, as github has a few restrictions to workflows created on branches that are not the default, like https://github.com/orgs/community/discussions/16107.

The discussion 16107 seems to suggest,
> "you still run the "current" workflow of the default branch where that checkout step is defined."

As the workflows are for now defined in main this should be okay for nightly scheduled builds. 
Are we observing issues with the nightly builds?

> 
> As this can impact the documentation (users would need to clone the right branch when consuming Qcom Linux), tracking this as an issue.

**Comment by ricardosalveti** [comment]
> Are we observing issues with the nightly builds?

Yes, the issue is with nightly builds only.

**Comment by sbanerjee-quic** [comment]
@mynameistechno I not able to switch default to main for this using GitHub provided guidelines on the page https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

Is this because this is under QuIC organization? Can you please try switching default to main?

**Comment by craigez** [comment]
Guessing it relates to admin permissions. This is done now.
