### ISSUE TITLE
ci: evaluate the benefits of using the github poky mirror

### ISSUE THREAD

**Issue by quaresmajose** [quic-yocto/meta-qcom-hwe#51]
There too many fail to access the poky upstream repository hosted on by yoctoproject
```
fatal: unable to access 'https://git.yoctoproject.org/git/poky/': gnutls_handshake() failed: Error in the pull function.
```
maybe if the existing https://github.com/yoctoproject/poky mirrors in the github infrastructure are used this will disappear.

**Comment by ricardosalveti** [comment]
@ndechesne said he had issues with yocto kernel as well, so while this would help for fetching the layers, it could still cause issues later, unless we have mirrors for everything.

**Comment by quaresmajose** [comment]
> @ndechesne said he had issues with yocto kernel as well, so while this would help for fetching the layers, it could still cause issues later, unless we have mirrors for everything.

for the others we have all of them on the persistent download folder, only the meta layers needs to be fully fetched from outside of the github infra in every ci job.

**Comment by ndechesne** [comment]
> > @ndechesne said he had issues with yocto kernel as well, so while this would help for fetching the layers, it could still cause issues later, unless we have mirrors for everything.
> 
> for the others we have all of them on the persistent download folder, only the meta layers needs to be fully fetched from outside of the github infra in every ci job.

the issue I had was during the get_rev() of linux-yocto-dev ;-) so the only case when we fetch from outside the persistent folder!

**Comment by quaresmajose** [comment]
To improve the situation we can also store the all the OE repo layers on the persistent storage so that they are not always erased and fetched again and again.

**Comment by ndechesne** [comment]
hmm. especially because we end up cloning the trees in each job actually! for kas-lock, yocto-check-layer and compile. we create the workspace each time!

**Comment by quaresmajose** [comment]
must be completed with https://github.com/quic-yocto/meta-qcom-hwe/pull/63

**Comment by ricardosalveti** [comment]
Still won't fix the issues identified as part of the recipes itself, but we can probably close this issue and evaluate again how often we will be getting new failures, as yocto did have some infra issues.
